---
abstract: 'Best Practical Builder'
author:
  - 'sunnavy <sunnavy@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  IPC::Cmd: 0
  Module::Build: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Shipwright
no_index:
  directory:
    - t
    - docs
    - share
    - inc
requires:
  Algorithm::Dependency::Ordered: 0
  Algorithm::Dependency::Source::HoA: 0
  App::CLI: 0
  Archive::Extract: 0
  Archive::Tar: 0
  CPAN: 1.9205
  CPAN::DistnameInfo: 0
  Class::Accessor::Fast: 0
  File::Copy: 0
  File::Copy::Recursive: 0
  File::Slurp: 0
  File::Spec: 0
  File::Temp: 0
  Hash::Merge: 0
  IO::Uncompress::Bunzip2: 0
  IO::Uncompress::RawInflate: 2.012
  IPC::Run3: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Log::Log4perl: 0
  Module::CoreList: 0
  Module::Info: 0
  UNIVERSAL::require: 0
  YAML::Syck: 0.71
  YAML::Tiny: 0
  perl: 5.8.8
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 2.000000
