--- 
abstract: Best Practical Builder
author: 
  - sunnavy  C<< <sunnavy@bestpractical.com> >>
build_requires: 
  Module::Build: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Shipwright
no_index: 
  directory: 
    - t
    - docs
    - inc
    - t
requires: 
  Algorithm::Dependency::Ordered: 0
  Algorithm::Dependency::Source::HoA: 0
  App::CLI: 0
  CPAN: 1.9205
  CPAN::DistnameInfo: 0
  Class::Accessor::Fast: 0
  File::Copy: 0
  File::Copy::Recursive: 0
  File::Slurp: 0
  File::Spec: 0
  File::Temp: 0
  Hash::Merge: 0
  IPC::Run3: 0
  LWP::UserAgent: 0
  Log::Log4perl: 0
  Module::CoreList: 0
  UNIVERSAL::require: 0
  YAML::Syck: 0.71
  version: 0
tests: t/*.t t/*/*.t
version: 1.01
